return {
	diagnostics = {
		Error = " ",
		Warn = " ",
		Hint = " ",
		Info = " ",
		-- Error = "",
		-- Warn = "",
		-- Hint = "",
		-- Info = "",
		-- Error = " ",
		-- Warn = " ",
		-- Hint = " " },
	},
	git = {
		Add = "",
		Mod = "",
		Remove = "",
	},
	kinds = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "ﰠ",
		Variable = "",
		Class = "ﴯ",
		Interface = "",
		Module = "",
		Property = "ﰠ",
		Unit = "U",
		Value = "",
		Enum = "了",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
}
